platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/RainyofSun/B_Category.git'

def all_Pods
    pod 'LRB_Category'
end

target 'A_section'do
   all_Pods
end

